name: Firmware Build

on:
  push:
    paths:
      - "firmware/**"
      - ".github/workflows/firmware-build.yml"
  pull_request:
    paths:
      - "firmware/**"
      - ".github/workflows/firmware-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.1

      - name: Build AirCube firmware (ESP32-H2)
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.2
          target: esp32h2
          path: firmware
